version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    
    schedule:
      interval: "cron"
      cronjob: "0 18 * * 1"

    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/tests"

    schedule:
      interval: "cron"
      cronjob: "0 18 * * 4"

    groups:
      all:
        patterns:
          - "*"
