[server.bind]
host = "0.0.0.0"
port = 5001

# Uncomment if behind a proxy

# [server.public]
# scheme = "http"
# host = "192.168.0.1"
# port = 5001

[database]
file_path = "persistence/database.db"
max_connections = 16
busy_timeout_seconds = 10
backup_before_migration = true

[prosa]
scheme = "http"
host = "127.0.0.1"
port = 5000

[kepub]
cache_size_mb = 256
